name: Deploy 🚀
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Host Variable
        run: |
          if [ -n "${{ secrets.HOST }}" ]; then
            echo "Host is set"
          else
            echo "Host is not set"
            exit 1
          fi

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          debug: true
          script: |
            cd /root/dtb
            git pull