name: Remote SSH Deploy
on:
  push:
    branches: [ main ]  # 或者你的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}  # 如果使用密码认证
          # key: ${{ secrets.SSH_PRIVATE_KEY }}  # 如果使用密钥认证
          script: |
            cd /root/dtb
            git pull